### ISSUE TITLE
Unable to start dev server

### ISSUE THREAD

**Issue by simeg** [mzabriskie/react-example#3]
After cloning the project, running `npm install` and then trying to start the dev server by `npm start` I am getting this error:

``` bash
ERROR in ./index.js
Module build failed: SyntaxError: /Users/Simon/repos/test/react-example/index.js: Unexpected token (14:2)
  12 | 
  13 | ReactDOM.render((
> 14 |   <Router history={appHistory}>
     |   ^
  15 |     <Route path="/" component={Home}/>
  16 |     <Route path="/:user" component={User}/>
  17 |   </Router>
```

I get the same error when I try to build the project using `npm build`. Any idea what might be wrong?

**Comment by kentcdodds** [comment]
Sorry, that was my bad. I accidentally forgot to commit the `.babelrc`. I'm working on this now and it should be fixed soon.

**Comment by kentcdodds** [comment]
Alrighty, you should be able to get things working now. Make sure to reinstall dependencies first :+1:
