### ISSUE TITLE
Tooltip broken

### ISSUE THREAD

**Issue by kentcdodds** [mzabriskie/react-example#4]
I'm not sure what happened, but somewhere in updating all dependencies I broke the tooltip. I've tried reverting and can't get it to work still. So I'm going to leave it for now and we can figure out how to fix it later.

**Comment by mzabriskie** [comment]
This works when I use `react-tooltip@0.8.3`. I'll keep looking to see what the breaking change is.

**Comment by mzabriskie** [comment]
`react-tooltip@3.0.0` works, `react-tooltip@3.0.1` does not.
