### ISSUE TITLE
Config Issue

### ISSUE THREAD

**Issue by even-today** [mzabriskie/react-example#8]
git clone git@github.com:mzabriskie/react-example.git
cd react-example
npm install
npm run validate (to generate bundle.js ... )
npm start
open http://127.0.0.1:8080

**Comment by even-today** [comment]
may be git clone should be https, that will be no worry about access error

**Comment by kentcdodds** [comment]
I'm sorry, so what problem are you having exactly?

**Comment by even-today** [comment]
e... Maybe .md file could add "npm run validate (to generate bundle.js ... )"...

**Comment by even-today** [comment]
just like: 
git clone https://github.com/mzabriskie/react-example.git
cd react-example
npm install
npm run validate (to generate bundle.js ... )
npm start
open http://127.0.0.1:8080

nothing about worrying...
It could be better...

**Comment by kentcdodds** [comment]
Oh, I understand. Yeah, we're working on the repo right now, sorry.

**Comment by even-today** [comment]
yeah, that's kind... If anything I could do to help you, pls contact me ...
I just want to do something good for open source pro.. 
Anything is OK..

**Comment by kentcdodds** [comment]
This has been improved.
